tasks:
  - init: echo "alias potigol='java -jar /workspace/gitpod/lib/potigol.jar 2> /dev/null'" >> ~/.bashrc
  - init: echo "alias potigol2scala='/workspace/gitpod/lib/potigol2scala'" >> ~/.bashrc
  - command: clear
