tasks:
  - before: cat lib/.bashrc >> ~/.bashrc
    command: source ~/.bashrc
    
  - openMode: split-bottom
    command: clear

vscode:
  extensions:
    - potigol.potigol-language@0.0.1:2164153fdfb14a9e9143f4f73e1042cc
