tasks:
  - before: cat lib/.bashrc >> ~/.bashrc
    command: source ~/.bashrc
    
  - openMode: tab-after
    command: potigol olamundo.poti

vscode:
  extensions:
    - potigol.potigol-language@0.0.1:2164153fdfb14a9e9143f4f73e1042cc
